In [3]:
import numpy as np

**Exercise 1: Create a NumPy array with values from 0 to 9. Use boolean indexing to select all numbers greater than 5.**


In [4]:
arr = np.arange(10)
np.where(arr > 5)

(array([6, 7, 8, 9], dtype=int64),)

**Exercise 2: Given arr = np.array([10, 20, 30, 40, 50]), create a boolean mask for elements greater than or equal to 30.**

In [7]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 30
filt_arr = arr[mask]
filt_arr

array([40, 50])

**Exercise 3: Using the same arr, replace all values greater than or equal to 30 with 0.**

In [9]:
arr[arr >= 30] = 0
arr

array([10, 20,  0,  0,  0])

**Exercise 4: Create a NumPy array from 1 to 12, reshape it into a 3x4 matrix, and select the second row.**

In [13]:
arr1 = np.arange(12)
arr1 = arr1.reshape((3, 4))
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
arr1[1]

array([4, 5, 6, 7])

**Exercise 5: Select the first two columns from the 3x4 matrix created in question 4.**

In [17]:
arr1[:, :2]

array([[0, 1],
       [4, 5],
       [8, 9]])

**Exercise 6: Create a 5x5 NumPy array of random integers between 1 and 100.    Select all elements that are divisible by 3.**


In [24]:
arr = (np.random.randint(1, 100, (5, 5)))
mask = arr % 3 == 0
divisible = arr[mask]
divisible

array([93, 18, 15, 21, 75,  6, 90, 96, 42])

**Exercise 7: Create an array with values from 0 to 19. Use fancy indexing to select elements at positions [1, 5, 10, 15].**


In [27]:
arr3 = np.arange(0, 19)
indices = [1, 5, 10, 15]
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [28]:
arr3[indices]

array([ 1,  5, 10, 15])

**Exercise 8: Given arr = np.array([1, 2, 3, 4, 5]), set the first three elements to -1 using slicing.**


In [29]:
arr = np.array([1, 2, 3, 4, 5])
arr[:3] = -1
arr

array([-1, -1, -1,  4,  5])

**Exercise 9: Create a 4x4 identity matrix and change the value in the bottom-right corner to 99.** 

In [35]:
rng = np.random
arr5 = np.arange(16)
arr5 = np.reshape(arr5, (4, 4))
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
arr5[3, 3] = 99
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 99]])

**Exercise 10: Create two arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]). Stack them vertically and horizontally using np.vstack() and np.hstack().**

In [38]:
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6])
vert_stack = np.vstack((arr1, arr2))
horiz_stack = np.hstack((arr1, arr2))

vert_stack

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
horiz_stack

array([1, 2, 3, 4, 5, 6])