**4.5 File Input and Output with Arrays**

Numpy can save and load data from the disk in some formats. Some functions to do that are *np.save* and *np.load*

In [8]:
import numpy as np

In [9]:
arr = np.arange(10)
np.save("arr", arr)

In [10]:
np.load("arr.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can save multiple arrays in an uncompressed archive using *numpy.savez*

In [11]:
np.savez("array_archive.npz", a=arr, b=arr)

When you load a *.npz* file, you get back a dictionary-like object that loads the individual arrays 

In [12]:
arch = np.load("array_archive.npz")
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arch['b'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**4.6 Linear Algebra**

In [14]:
x = np.array([[1., 2., 3.], [4., 5.,   6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

*.dot* and *np.dot()* are both for matrix multiplication

In [16]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [17]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [18]:
x @ np.ones(3)

array([ 6., 15.])

The *numpy.linalg* library has many matrix decompositions and things like *inverse* and *determinant*

In [19]:
from numpy.linalg import inv, qr
rng = np.random 
X = rng.standard_normal((5, 5))

In [20]:
mat = X.T @ X

In [21]:
inv(mat)

array([[ 0.20924205,  0.40287765,  0.28662224, -0.33951757, -0.02465971],
       [ 0.40287765,  1.88257788,  1.41266036, -1.37192848, -0.09134002],
       [ 0.28662224,  1.41266036,  1.28493957, -1.10485417, -0.12396647],
       [-0.33951757, -1.37192848, -1.10485417,  1.29242376,  0.04422293],
       [-0.02465971, -0.09134002, -0.12396647,  0.04422293,  0.14075124]])