**Exercise 1: Create a NumPy array with values [1, 4, 9, 16, 25] and use np.sqrt to compute the square root of each element.**

In [2]:
import numpy as np

In [8]:
arr = np.array([1, 4, 9, 16, 25])
np.sqrt(arr)

array([1., 2., 3., 4., 5.])

**Exercise 2: Given arr = np.array([1.2, 3.8, -2.5, -4.9]), use np.floor to round each element down.**

In [9]:
arr = np.array([1.2, 3.8, -2.5, -4.9])
np.floor(arr)

array([ 1.,  3., -3., -5.])

In [10]:
np.ceil(arr)

array([ 2.,  4., -2., -4.])

**Exercise 3: Create two arrays: arr1 = [1, 2, 3] and arr2 = [4, 5, 6]. Use np.add to add them element-wise.**


In [11]:
arr1 = [1, 2, 3] 
arr2 = [4, 5, 6]


np.add(arr1, arr2)

array([5, 7, 9])

**Exercise 4: Using arr1 and arr2, use np.maximum to get the element-wise maximum values.**


In [12]:
np.maximum(arr1, arr2)

array([4, 5, 6])

**Exercise 5: Create a NumPy array with 5 values between 0 and 2π and use np.sin to compute their sine values.**

In [13]:
pi_array = np.linspace(0, 2*np.pi, 5)
pi_array

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])