**4.3 Universal Functions: Fast Element-Wise Array Functions**

An *ufunc* is a function that performs element-wise operations on data in  ndarrays

In [3]:
import numpy as np


arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

np.exp() is Euler's Number to the power of each number in the array, basically e^x for x in arr

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

The above functions are referred to as *unary* ufuncs, and the below functions are *binary* ufuncs.

In [8]:
rng = np.random.default_rng()

x = rng.standard_normal(8)

y = rng.standard_normal(8)

x

array([ 1.57430415,  1.24196732,  0.72647537, -0.2787623 , -0.16880054,
       -1.0022526 , -0.17120514,  0.15635623])

In [9]:
y

array([-0.10367321,  1.04484717,  0.84886972,  1.19118557, -0.81542347,
       -1.36120634, -1.14141358,  0.14279467])

np.maximum() computes the element-wise maximum in both arrays

In [10]:
np.maximum(x, y)

array([ 1.57430415,  1.24196732,  0.84886972,  1.19118557, -0.16880054,
       -1.0022526 , -0.17120514,  0.15635623])

Sometimes, an ufunc can return multiple arrays, like np.modf

In [12]:
arr = rng.standard_normal(7) * 5
arr

array([-6.83329627, -0.73004607, -8.4984833 , -2.77344271, -1.7388157 ,
        6.74090261, 10.07745973])

In [13]:
remainder, whole_part = np.modf(arr)

remainder

array([-0.83329627, -0.73004607, -0.4984833 , -0.77344271, -0.7388157 ,
        0.74090261,  0.07745973])

In [14]:
whole_part

array([-6., -0., -8., -2., -1.,  6., 10.])

Ufuncs have an optional *out* argument that allows them to assign their results to an existing array

In [20]:
arr

array([-6.83329627, -0.73004607, -8.4984833 , -2.77344271, -1.7388157 ,
        6.74090261, 10.07745973])

In [21]:
out = np.zeros_like(arr)

In [22]:
np.add(arr, 1)

array([-5.83329627,  0.26995393, -7.4984833 , -1.77344271, -0.7388157 ,
        7.74090261, 11.07745973])

In [23]:
np.add(arr, 1, out=out)

array([-5.83329627,  0.26995393, -7.4984833 , -1.77344271, -0.7388157 ,
        7.74090261, 11.07745973])

In [24]:
out

array([-5.83329627,  0.26995393, -7.4984833 , -1.77344271, -0.7388157 ,
        7.74090261, 11.07745973])