**4.1 The Numpy Array:**

In [88]:
import numpy as np
data = np.array([[1, 2, 3], [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
type(data)

numpy.ndarray

You can perform mathematical operations on ndarrays:

In [90]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12]])

You can get the shape of a ndarray using *.shape*. This is in the format of a grid, ex. '5x5' would be (5, 5)

In [91]:
data.shape

(2, 3)

You can use *.dtype* for getting the data type of the values inside the ndarray

In [92]:
data.dtype

dtype('int32')

Ndarrays are typically *homogenous*, meaning that all elements must be the same data type.

**Creating Ndarrays**

In [93]:
data1 = [6, 7, 8, 3, 4,]
arr1 = np.array(data1)
arr1

array([6, 7, 8, 3, 4])

Nested sequences will be converted into a *multidimensional array*

In [94]:
data2 = [[2.2, 3, 1, 4], [6, 7, 5, 8]]
arr2 = np.array(data2)
arr2

array([[2.2, 3. , 1. , 4. ],
       [6. , 7. , 5. , 8. ]])

Since data2 was a list of lists, that means it has 2 dimensions, and this can be confirmed using *ndim* and *shape*

In [95]:
arr2.ndim

2

In [96]:
arr2.shape

(2, 4)

When a *ndarray* is created, Numpy tries to find a good data tyype for the array it creates

In [97]:
arr1.dtype

dtype('int32')

In [98]:
arr2.dtype

dtype('float64')

There are other ways to create new arrays, like the *np.zeros* and *np.ones*, which creates arrays full of zeroes and ones, respectively

In [99]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [100]:
np.ones((6, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

Also, *np.empty* creates an array without initializing its values, and basically returns unitialized memory, resulting in 'junk values', so this is not recommenrded to be used in place of *np.zeroes*

In [101]:
np.empty((2, 3, 2))

array([[[1.07480864e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 1.33664410e+160]],

       [[7.17570936e-091, 7.24776312e-042],
        [6.54511202e-043, 1.34724489e+165],
        [3.99910963e+252, 4.93432906e+257]]])

*np.arange()* is a function similar to python's range function, but it returns a array of the range that was inserted

In [102]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Data Types for Ndarrays**

You can specify the *dtype* or *data type* by using *dtype=*

In [103]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [104]:
arr1.dtype

dtype('float64')

You can convert an array from one data type to another using *astype()*

In [105]:
arr1int = arr1.astype(np.int32)
arr1int

array([1, 2, 3])

In [106]:
arr1int.dtype

dtype('int32')

If floats are converted to ints, the decimal part will be removed

In [107]:
arr2.dtype

dtype('float64')

In [108]:
arr2

array([[2.2, 3. , 1. , 4. ],
       [6. , 7. , 5. , 8. ]])

In [109]:
arrint = arr2.astype(np.int32)
arrint

array([[2, 3, 1, 4],
       [6, 7, 5, 8]])

If you have strings representing numbers, *astype* can be used to convert them to numeric form

In [115]:
num_strings = np.array([['1', '2', '3'], ['4', '5', '6']])
num_strings

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [116]:
nums = num_strings.astype(np.int32)
nums

array([[1, 2, 3],
       [4, 5, 6]])

You can also use another array's dtype attribute to change an array

In [117]:
num_ints = num_strings.astype(arrint.dtype)
num_ints

array([[1, 2, 3],
       [4, 5, 6]])

**Artithmetic with Numpy Arrays**

In [120]:
arr1

array([1., 2., 3.])

Arrays are important because they are able to use *vectorization*, which is when an operation is just done to all elements at once, instead of using a for loop to do the operation to each individual element. 

In [119]:
arr1 * arr1

array([1., 4., 9.])

In [122]:
arr1*2

array([2., 4., 6.])

Comparing 2 arrays of the same size will return a boolean array

In [124]:
arr = np.array([1, 4, 3])
arr1 = np.array([2, 3, 6])
arr > arr1

array([False,  True, False])

**Basic Indexing and Slicing**

One-dimensional arrays can be indexed like a normal python list

In [125]:
arr = np.arange(10)

In [126]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
arr[5]

5

You can use slicing to assign values in an array

In [130]:
arr[5:8] = 67

In [131]:
arr

array([ 0,  1,  2,  3,  4, 67, 67, 67,  8,  9])

You can create *slices* of an array, and the changes you make to the slice will be reflected in the original array

In [132]:
arr_slice = arr[5:8]
arr_slice[:] = 76
arr

array([ 0,  1,  2,  3,  4, 76, 76, 76,  8,  9])

With multidimensional arrays, the elements at indexes turn into their own lists

In [134]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

You can pass a comma-separated list to select the elements inside the nested list, or you can use multiple one-element lists

In [135]:
arr2d[2, 2]

9

In [136]:
arr2d[2][2]

9

**Indexing with Slices**

In [138]:
arr

array([ 0,  1,  2,  3,  4, 76, 76, 76,  8,  9])

In [141]:
arr[:2]

array([0, 1])

Indexing through our 2d array is a little different

In [139]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])